//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace English2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tt_bangDiem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tt_bangDiem()
        {
            this.tt_ctBangDiem = new HashSet<tt_ctBangDiem>();
        }
    
        public int maBD { get; set; }
        public int maLop { get; set; }
        public string htKiemTra { get; set; }
        public Nullable<System.DateTime> ngayKT { get; set; }
        public Nullable<int> lanThu { get; set; }
        public Nullable<int> heSo { get; set; }
        public string tenGoi { get; set; }
        public Nullable<int> thoiGian { get; set; }
        public string noiDung { get; set; }
        public string nhanXet { get; set; }
        public string ghiChu { get; set; }
    
        public virtual tt_lopHoc tt_lopHoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tt_ctBangDiem> tt_ctBangDiem { get; set; }
    }
}
