//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace English2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tt_chiNhanh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tt_chiNhanh()
        {
            this.tt_chiTien = new HashSet<tt_chiTien>();
            this.tt_lopHoc = new HashSet<tt_lopHoc>();
            this.tt_phongHoc = new HashSet<tt_phongHoc>();
            this.tt_thanhVien = new HashSet<tt_thanhVien>();
            this.tt_thuTien = new HashSet<tt_thuTien>();
        }
    
        public int maCN { get; set; }
        public string tenCN { get; set; }
        public string maST { get; set; }
        public Nullable<System.DateTime> ngayTL { get; set; }
        public string maDD { get; set; }
        public int thuTu { get; set; }
        public string diaChi { get; set; }
        public string quanHuyen { get; set; }
        public string tinhTP { get; set; }
        public string soDT { get; set; }
        public string soFAX { get; set; }
        public string email { get; set; }
        public string ghiChu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tt_chiTien> tt_chiTien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tt_lopHoc> tt_lopHoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tt_phongHoc> tt_phongHoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tt_thanhVien> tt_thanhVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tt_thuTien> tt_thuTien { get; set; }
    }
}
