//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace English2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tt_caHoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tt_caHoc()
        {
            this.tt_dangKyGD = new HashSet<tt_dangKyGD>();
            this.tt_lichHoc = new HashSet<tt_lichHoc>();
            this.tt_nhatKyGD = new HashSet<tt_nhatKyGD>();
        }
    
        public int maCa { get; set; }
        public int buoiHoc { get; set; }
        public string tenCa { get; set; }
        public string kyHieu { get; set; }
        public System.DateTime batDau { get; set; }
        public int thoiLuong { get; set; }
        public string ghiChu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tt_dangKyGD> tt_dangKyGD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tt_lichHoc> tt_lichHoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tt_nhatKyGD> tt_nhatKyGD { get; set; }
    }
}
