//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace English2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tt_ctChuongTrinh
    {
        public int maCT { get; set; }
        public int maMon { get; set; }
        public Nullable<int> thoiLuong { get; set; }
        public string dvt { get; set; }
        public string ghiChu { get; set; }
    
        public virtual tt_chuongTrinh tt_chuongTrinh { get; set; }
        public virtual tt_monHoc tt_monHoc { get; set; }
    }
}
