//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace English2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tt_ctBangDiem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tt_ctBangDiem()
        {
            this.tt_kqLamBai = new HashSet<tt_kqLamBai>();
        }
    
        public int maDiem { get; set; }
        public int maBD { get; set; }
        public string maHS { get; set; }
        public double diemSo { get; set; }
    
        public virtual tt_bangDiem tt_bangDiem { get; set; }
        public virtual tt_hocSinh tt_hocSinh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tt_kqLamBai> tt_kqLamBai { get; set; }
    }
}
