//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace English2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tt_chuongTrinh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tt_chuongTrinh()
        {
            this.tt_ctChuongTrinh = new HashSet<tt_ctChuongTrinh>();
            this.tt_lopHoc = new HashSet<tt_lopHoc>();
        }
    
        public int maCT { get; set; }
        public string tenCT { get; set; }
        public string loaiCT { get; set; }
        public Nullable<int> thoiLuong { get; set; }
        public string dvt { get; set; }
        public long hocPhi { get; set; }
        public string vietTat { get; set; }
        public string ghiChu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tt_ctChuongTrinh> tt_ctChuongTrinh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tt_lopHoc> tt_lopHoc { get; set; }
    }
}
