//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace English2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tt_chiTien
    {
        public int maCN { get; set; }
        public int idChiTien { get; set; }
        public string soPhieuChi { get; set; }
        public System.DateTime ngayChi { get; set; }
        public long chietKhau { get; set; }
        public long soTien { get; set; }
        public string noiDung { get; set; }
        public string nguoiNhan { get; set; }
        public string dcNguoiNhan { get; set; }
        public Nullable<int> hinhThucChi { get; set; }
        public int maTV { get; set; }
        public string ghiChu { get; set; }
        public Nullable<bool> biHuy { get; set; }
    
        public virtual tt_chiNhanh tt_chiNhanh { get; set; }
        public virtual tt_thanhVien tt_thanhVien { get; set; }
    }
}
