//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace English2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tt_donTu
    {
        public int maDon { get; set; }
        public int maLop { get; set; }
        public Nullable<int> chuyenDen { get; set; }
        public string maHS { get; set; }
        public int mucDich { get; set; }
        public string nguoiLD { get; set; }
        public long soTienDaDong { get; set; }
        public string bienlaiGoc { get; set; }
        public int soBuoiDaHoc { get; set; }
        public long soTienDaRut { get; set; }
        public long soTienBaoLuu { get; set; }
        public Nullable<System.DateTime> thoiHanBL { get; set; }
        public int trangThai { get; set; }
        public Nullable<System.DateTime> ngayNop { get; set; }
        public Nullable<System.DateTime> ngayDuyet { get; set; }
        public string ghiChu { get; set; }
    
        public virtual tt_lopHoc tt_lopHoc { get; set; }
        public virtual tt_hocSinh tt_hocSinh { get; set; }
        public virtual tt_lopHoc tt_lopHoc1 { get; set; }
    }
}
