//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace English2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tt_danhGiaHS
    {
        public int maLop { get; set; }
        public string maHS { get; set; }
        public string chuyenCan { get; set; }
        public Nullable<int> tinhThanHT { get; set; }
        public Nullable<int> phuongPhapHT { get; set; }
        public string btVeNha { get; set; }
        public string diemKT { get; set; }
        public string nhanXet { get; set; }
        public string ykPhuHuynh { get; set; }
        public int maTV { get; set; }
        public string ghiChu { get; set; }
    
        public virtual tt_lopHoc tt_lopHoc { get; set; }
        public virtual tt_hocSinh tt_hocSinh { get; set; }
        public virtual tt_thanhVien tt_thanhVien { get; set; }
    }
}
