//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace English2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tt_diemDanh
    {
        public int maNKGD { get; set; }
        public string maHS { get; set; }
        public Nullable<int> tinhTrang { get; set; }
        public string lyDo { get; set; }
        public Nullable<bool> daBaoPH { get; set; }
        public string btDaLam { get; set; }
        public string thoiGian { get; set; }
    
        public virtual tt_nhatKyGD tt_nhatKyGD { get; set; }
        public virtual tt_hocSinh tt_hocSinh { get; set; }
    }
}
