//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace English2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tt_dangKyGD
    {
        public int maTV { get; set; }
        public int maMon { get; set; }
        public int maCa { get; set; }
        public string thuTT { get; set; }
    
        public virtual tt_caHoc tt_caHoc { get; set; }
        public virtual tt_monHoc tt_monHoc { get; set; }
        public virtual tt_thanhVien tt_thanhVien { get; set; }
    }
}
