//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace English2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tt_kqLamBai
    {
        public int maDiem { get; set; }
        public int cauSo { get; set; }
        public Nullable<double> diemCau { get; set; }
    
        public virtual tt_ctBangDiem tt_ctBangDiem { get; set; }
    }
}
