//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace English2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tt_lichHoc
    {
        public int maLop { get; set; }
        public int maPhong { get; set; }
        public int maCa { get; set; }
        public int thu { get; set; }
        public string ghiChu { get; set; }
    
        public virtual tt_caHoc tt_caHoc { get; set; }
        public virtual tt_lopHoc tt_lopHoc { get; set; }
        public virtual tt_phongHoc tt_phongHoc { get; set; }
    }
}
