//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace English2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tt_phongHoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tt_phongHoc()
        {
            this.tt_lichHoc = new HashSet<tt_lichHoc>();
            this.tt_nhatKyGD = new HashSet<tt_nhatKyGD>();
        }
    
        public Nullable<int> maCN { get; set; }
        public int maPhong { get; set; }
        public string tenPhong { get; set; }
        public Nullable<bool> hoatDong { get; set; }
        public Nullable<int> sucChua { get; set; }
        public Nullable<bool> coProjector { get; set; }
        public Nullable<bool> coTiVi { get; set; }
        public string ghiChu { get; set; }
    
        public virtual tt_chiNhanh tt_chiNhanh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tt_lichHoc> tt_lichHoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tt_nhatKyGD> tt_nhatKyGD { get; set; }
    }
}
