//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace English2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tt_thanhVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tt_thanhVien()
        {
            this.tt_chiTien = new HashSet<tt_chiTien>();
            this.tt_dangKyGD = new HashSet<tt_dangKyGD>();
            this.tt_danhGiaHS = new HashSet<tt_danhGiaHS>();
            this.tt_dsGiaoVienLop = new HashSet<tt_dsGiaoVienLop>();
            this.tt_hocSinhTuVan = new HashSet<tt_hocSinhTuVan>();
            this.tt_nhatKyGD = new HashSet<tt_nhatKyGD>();
            this.tt_taiKhoan = new HashSet<tt_taiKhoan>();
            this.tt_thuTien = new HashSet<tt_thuTien>();
        }
    
        public int maTV { get; set; }
        public string hoTV { get; set; }
        public string tenTV { get; set; }
        public string htVietTat { get; set; }
        public int gioiTinh { get; set; }
        public System.DateTime ngaySinh { get; set; }
        public string noiSinh { get; set; }
        public string quocTich { get; set; }
        public string soDT { get; set; }
        public string eMail { get; set; }
        public Nullable<int> honNhan { get; set; }
        public string dcLienLac { get; set; }
        public string dcThuongTru { get; set; }
        public string soCMND { get; set; }
        public string noiCapCMND { get; set; }
        public Nullable<System.DateTime> ngayCapCMND { get; set; }
        public string chucDanh { get; set; }
        public Nullable<System.DateTime> ngayNhanViec { get; set; }
        public string hocVi { get; set; }
        public string chuyenMon { get; set; }
        public string ngoaiNgu { get; set; }
        public string tinHoc { get; set; }
        public string kyNangKhac { get; set; }
        public string hinhCN { get; set; }
        public Nullable<int> maCN { get; set; }
        public Nullable<int> maPB { get; set; }
        public string qhGiaDinh { get; set; }
    
        public virtual tt_chiNhanh tt_chiNhanh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tt_chiTien> tt_chiTien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tt_dangKyGD> tt_dangKyGD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tt_danhGiaHS> tt_danhGiaHS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tt_dsGiaoVienLop> tt_dsGiaoVienLop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tt_hocSinhTuVan> tt_hocSinhTuVan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tt_nhatKyGD> tt_nhatKyGD { get; set; }
        public virtual tt_phongBan tt_phongBan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tt_taiKhoan> tt_taiKhoan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tt_thuTien> tt_thuTien { get; set; }
    }
}
